### PR TITLE
feat(crud): added CrudAuth decorator

### PR DESCRIPTION
**Pull request by zMotivat0r**
Enables the possibility to use filtering by an authorized user and persist some data on
create/update

re #229

Usage:

https://github.com/nestjsx/crud/blob/4dfa2987a7e0e78b13facd778ee72aa374ed156f/packages/crud-typeorm/test/d.crud-auth.spec.ts#L40-L66

### CODE REVIEW

**Comment by omerxx** [comment]
Thank you for that!
Is this in the docs somewhere we can read and use?

**Comment by DaVarga** [comment]
Hi @zMotivat0r 

I like the approach of being able to filter the results of an endpoint based on information from the request. 

Is there a way to check whether the request user is part of a list in the object he wants to access? Let's say there is an entity which contains a list called `trustedUsers`. Is there a way to filter on this relation?

Does something like work?
```ts
    @CrudAuth({
      property: 'user',
      filter: (user: User) => ({
        'trustedUsers.id': user.id,
      }),
    })
```

**Comment by zMotivat0r** [comment]
Yes, it should work if `trustedUsers` is the relation name and if this relation was added in the `CrudOptions.query.join` with `eager: true` or requested implicitly in a query.

**Comment by DaVarga** [comment]
Nice. Works great. :+1: 

However, I noticed two things:
First,
```ts
    @CrudAuth({
      property: 'user',
      filter: (user: User) => ({
        'trustedUsers.id': [1, 2],
      }),
    })
```
doesn't work because it results in an AND operation and the result is always empty.
Is that intentional? In my opinion this should be an OR.

Second, is there a way to use an operator other than eq? I think != and >, <, and so on could be useful. Imagine the following usecases
```ts
filter: (user: User) => ({
  'bannedUsers.id': {operator: 'neq', value: user.id},
}),
filter: (user: User) => ({
  'reqAccessLevel': {operator: 'lte', value: user.accessLevel},
}),
```
maybe it should be possible to return `Array<QueryFilter>` instead of `ObjectLiteral` for such more complex cases?

**Comment by zMotivat0r** [comment]
It's already working as a new `search` param that was introduced with this PR https://github.com/nestjsx/crud/pull/265
So in your case, you need this: 
```typescript
filter: (user: User) => ({
  'trustedUsers.id': {
    $eq: 1,
    $or: {
      $eq: 2,
    },
  },
}),
```

**Comment by DaVarga** [comment]
This is awesome! Thanks mate :)

**Comment by kereslas** [comment]
Hi @zMotivat0r ,

I have a table of books that uses CrudAuth to filter by bookstore:

```
@CrudAuth({
  filter: (user: User) => ({
    storeId: user.store.id,
  }),
  persist: (user: User) => ({
    storeId: user.store.id,
  }),
})

```
When I make a query like this:

/books?filter=title||cont||Quijote&or=author||cont||Cervantes

It returns all books of the store, not only Quijote. The resulting SQL query adds a WHERE like this:
```
WHERE (Book.storeId = ?) OR `Book`.`title` LIKE ? OR `Book`.`author` LIKE ? -- PARAMETERS: [1,"%Quijote%","%Cervantes%"]
```
As you can see the separation between the auth parameter and the others is made with an OR, but I was specting an AND, as I suppose authentication is always an extrict filter. Is an OR the expected behavior?

If I don't use an OR in the REST call (not adding the author filter), then it uses an AND as expected.

Thanks for your work!

**Comment by DaVarga** [comment]
@kereslas This seems like a critical bug.
@zMotivat0r any workaround on that?

**Comment by codepushr** [comment]
This decorator isn't documented, isn't it?

**Comment by zMotivat0r** [comment]
@codepushr the whole `4.3.0` features/changes haven't been documented yet. I'm doing it at the moment. Planing to release today

**Comment by codepushr** [comment]
This feature is a killer, I almost gave up on this package, then I found this issue and it solved all my problems. Thanks a bunch!

**Comment by zMotivat0r** [comment]
@codepushr it now has `filter`, `or`, `persist` to cover a different query scenarious

**Comment by BovineEnthusiast** [comment]
Is it possible to apply this filter to only the `join` query? For example if you had an `Organization` controller and you wanted to join the user's `OrganizationPermissions` to a `GET Organization` request. My understanding is the `filter` param filters which `Organization` you can get, not which `OrganizationPermissions` you can get in a `join`.

**Comment by BovineEnthusiast** [comment]
After playing around with it, the answer to my question is 

> Yes, you can filter the joined relations because all this does is add an `AND {...}` to the `WHERE` clause at the end.

However, I have another question. In order to do this, I have to join the other tables. I only want to join them so that I can run the filter query above. I don't want to return them. If I try to use 'allow' or 'exclude' under `query`, it still includes the relations. Is there another way to modify the `SELECT` portion of the query not to include the relations?

**Comment by zMotivat0r** [comment]
@BovineEnthusiast you can use [serialization](https://github.com/nestjsx/crud/wiki/Controllers#serialize) and exclude fields from the response

**Comment by marcovelarde** [comment]
I have a entity with two user foreign key, ``user`` and ``userMod``. I want set ``user`` only when create and ``userMod``  when create/update. 
Exist any way for do this with ``persist`` option?

**Comment by marcovelarde** [comment]
I have a entity with two user foreign key, ``user`` and ``userMod``. I want set ``user`` only when create and ``userMod`` when create/update.
Exist any way to do this with ``persist`` option?

**Pull request merged**
