### PR TITLE
WIP: TypeORM Mongoose

### PR DESCRIPTION
**Pull request by douglasgc**

### CODE REVIEW

**Comment by zMotivat0r** [comment]
It's in progress, as I can see, right?

**Comment by lapwat** [comment]
Hello @douglasgc, how is the Mongoose integration going on ?

**Comment by douglasgc** [comment]
It works for me, but it is not stable, has no tests and no code pattern review.
But I'm still working on it.

**Comment by zMotivat0r** [comment]
@douglasgc I'm gonna close this because we'll create `@nestjsx/crud-mongoose` anytime soon

**Pull request closed without merging**
