### PR TITLE
feat(crud-typeorm): Adds alwaysPaginate global option and makes pagin…

### PR DESCRIPTION
**Pull request by jdguzman**
…ation default

BREAKING CHANGE: getManyBase now returns a paginated result by default unless opted out by setting
`alwaysPaginate: false`

re #213

### CODE REVIEW

**Comment by jdguzman** [comment]
@zMotivat0r I was unsure how to handle the need for a limit if `alwaysPaginate` is true and none is given. Some feedback there would be appreciated.

**Comment by zMotivat0r** [comment]
@jdguzman 
>but the UI doesn't really help in identifying which one. 

Actually it does. You can open `coverage/lcov-report/index.html` and there will be all the information needed. I always do this when I need to see what branches or statements coverage is missing

**Comment by jdguzman** [comment]
> Actually it does. You can open `coverage/lcov-report/index.html` and there will be all the information needed. I always do this when I need to see what branches or statements coverage is missing

@zMotivat0r Ah ... good to know. Locally jest was saying everything was good so I assumed the files you mentioned wouldn't be much help. I'll use those next time though. I was able to figure out what Coveralls was complaining about anyway and resolved that.

Any feedback on the PR itself?

**Comment by jdguzman** [comment]
@zMotivat0r wondering if you've had a chance to look at this?

**Comment by ashiemke** [comment]
@zMotivat0r any chance this could make it in? Would be super handy to have.

**Comment by kuklei** [comment]
Any chance this will make it into the next iteration? I see an ALPHA is already out.

**Pull request merged**
